name: jingdong_financial
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.0
  - pip==25.1.1
  - pip:
      - Cython==3.1.2
      - fastapi[all]==0.115.13
      - inject==5.2.1
      - dacite==1.6.0
      - celery==5.5.3
      - dynaconf==3.2.11
      - celery-redbeat==2.3.2
      - PyMySQL==1.1.1
      - SQLAlchemy==2.0.41
      - redis==6.2.0
      - PyJWT==2.10.1
      - orjson==3.10.18
      - psutil==7.0.0
      - requests==2.32.4
      - gunicorn==23.0.0
      - asyncer==0.0.8
      - numpy==2.3.0
      - python-redis-lock==4.0.0
      - git+https://github.com/softpeng/WorkWeChatSDK.git
      - pymannkendall==1.4.3
      - itunespy==1.6.1
      - musicbrainzngs==0.7.1
      - spotipy==2.25.1
      - yt-dlp==2025.6.30
      - ffmpeg-python==0.2.0
      - mutagen==1.47.0
      - ytmusicapi==1.10.3
      - downloader-cli==0.3.4
      - opencc-python-reimplemented
      - synology-api==0.7.1
      - bs4==0.0.2
      - pyyaml==6.0.2
      - supervisor==4.3.0
      # for dev
      - pytest==8.4.1
      - pytest-cover==3.0.0
      - pytest-order==1.3.0
      - pre-commit==4.2.0
      - pylint==3.3.7
      - mypy==1.16.1
      - black==25.1.0
      - isort==6.0.1
      - pycln==2.5.0
      - pytest-asyncio==1.0.0
